### ISSUE TITLE
TypeError: new() received an invalid combination of arguments - got (numpy.int64, numpy.int64, int)

### ISSUE THREAD

**Issue by hzxie** [matheusgadelha/MRTNet#9]
Traceback (most recent call last):
  File "run_img2pc.py", line 51, in <module>
    name=full_name, pretrained=ptrain, arch=args.arch)
  File "/mnt/lustre/xiehaozhe/Development/MRTNet/models/ImageToShape.py", line 50, in __init__
    in_channels, out_channels)
  File "/mnt/lustre/xiehaozhe/Development/MRTNet/models/AutoEncoder.py", line 188, in __init__
    name, in_channels, out_channels, nn.ConvTranspose1d, activation=activation)
  File "/mnt/lustre/xiehaozhe/Development/MRTNet/models/AutoEncoder.py", line 130, in __init__
    padding=0))
  File "/mnt/lustre/xiehaozhe/Applications/anaconda3/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 552, in __init__
    True, output_padding, groups, bias)
  File "/mnt/lustre/xiehaozhe/Applications/anaconda3/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 30, in __init__
    in_channels, out_channels // groups, *kernel_size))
TypeError: new() received an invalid combination of arguments - got (numpy.int64, numpy.int64, int), but expected one of:
 * (torch.device device)
 * (tuple of ints size, torch.device device)
 * (torch.Storage storage)
 * (Tensor other)
 * (object data, torch.device device)

**Comment by matheusgadelha** [comment]
This seems like an issue with the PyTorch version. It should work fine on PyTorch 0.4

**Comment by SmitSheth** [comment]
@hzxie How did you solve the issue?

**Comment by hzxie** [comment]
@SmitSheth 
Sorry, I forgot.
